# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e041c0498ba2e00d46c39ecc4c8fadd"
name = "revenue-challenge"
application_url = "https://keith-rapid-behavior-takes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "revenue-challenge.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://keith-rapid-behavior-takes.trycloudflare.com/auth/callback",
  "https://keith-rapid-behavior-takes.trycloudflare.com/auth/shopify/callback",
  "https://keith-rapid-behavior-takes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
